<template>
  <AdminLayout>
    <main class="page"><h1>Xử lý thực phẩm hết hạn</h1><p class="lead">Theo dõi, tiêu hủy và kiểm soát các lô nguyên liệu theo cùng dữ liệu cảnh báo kho.</p>
      <div class="kpis"><div><b>{{ expired.length }}</b><span>Hết hạn</span></div><div><b>{{ expiring.length }}</b><span>Sắp hết hạn</span></div><div><b>{{ disposed.length }}</b><span>Đã xử lý</span></div></div>
      <section class="card"><div class="section-head"><h2>Lô cần xử lý</h2><button class="danger" :disabled="!expired.length" @click="openBulk">Tiêu hủy toàn bộ</button></div><table><thead><tr><th>Nguyên liệu</th><th>Số lượng</th><th>Hạn dùng</th><th>Thao tác</th></tr></thead><tbody><tr v-for="batch in expired" :key="batch.id"><td>{{ nameOf(batch.ingredientId) }}</td><td>{{ batch.quantity }}</td><td>{{ date(batch.expirationDate) }}</td><td><button @click="dispose(batch)">Tiêu hủy</button></td></tr><tr v-if="!expired.length"><td colspan="4">Không có lô hết hạn.</td></tr></tbody></table></section>
      <section class="card"><h2>Lô sắp hết hạn</h2><table><thead><tr><th>Nguyên liệu</th><th>Số lượng</th><th>Hạn dùng</th></tr></thead><tbody><tr v-for="batch in expiring" :key="batch.id"><td>{{ nameOf(batch.ingredientId) }}</td><td>{{ batch.quantity }}</td><td>{{ date(batch.expirationDate) }}</td></tr><tr v-if="!expiring.length"><td colspan="3">Không có lô sắp hết hạn.</td></tr></tbody></table></section>
      <section class="card"><h2>Lịch sử tiêu hủy</h2><table><thead><tr><th>Nguyên liệu</th><th>Số lượng</th><th>Lý do</th><th>Ngày</th></tr></thead><tbody><tr v-for="item in disposed" :key="item.id"><td>{{ item.ingredientName }}</td><td>{{ item.quantityDisposed }}</td><td>{{ item.reason }}</td><td>{{ date(item.disposalDate) }}</td></tr><tr v-if="!disposed.length"><td colspan="4">Chưa có lịch sử.</td></tr></tbody></table></section>
    </main><div v-if="modalOpen" class="overlay" @click.self="closeModal"><div class="modal"><h2>{{ bulkOpen ? 'Tiêu hủy toàn bộ lô hết hạn' : 'Tiêu hủy lô nguyên liệu' }}</h2><p v-if="bulkOpen">Bạn sắp tiêu hủy {{ expired.length }} lô hết hạn ({{ bulkQuantity }} đơn vị). Hành động này không thể hoàn tác.</p><p v-else><b>{{ nameOf(selected.ingredientId) }}</b> · {{ selected.quantity }} · hạn {{ date(selected.expirationDate) }}</p><label>Lý do tiêu hủy<textarea v-model="reason" maxlength="500" placeholder="Nhập lý do bắt buộc..."></textarea></label><div class="modal-actions"><button class="secondary" @click="closeModal">Hủy</button><button class="danger" :disabled="!reason.trim() || submitting" @click="submitDisposal">{{ submitting ? 'Đang xử lý...' : (bulkOpen ? 'Xác nhận tiêu hủy toàn bộ' : 'Xác nhận tiêu hủy') }}</button></div></div></div>
  </AdminLayout>
</template>
<script setup>
import { ref, computed, onMounted } from 'vue';
import AdminLayout from '@/components/AdminLayout.vue';
import api from '@/services/api';
import { useToast } from '@/composables/useToast';
const toast = useToast(); const expired = ref([]); const expiring = ref([]); const disposed = ref([]); const ingredients = ref([]); const modalOpen = ref(false); const bulkOpen = ref(false); const selected = ref(null); const reason = ref(''); const submitting = ref(false);
const bulkQuantity = computed(() => expired.value.reduce((sum, batch) => sum + Number(batch.quantity || 0), 0));
const headers = () => ({ headers: { Authorization: `Bearer ${sessionStorage.getItem('staff_token')}` } });
const load = async () => { const results = await Promise.allSettled([api.get('/api/admin/ingredients', headers()), api.get('/api/admin/ingredients/expired-batches', headers()), api.get('/api/admin/ingredients/expiring-batches?daysThreshold=3', headers()), api.get('/api/admin/ingredients/disposed-batches', headers())]); if (results[0].status === 'fulfilled') ingredients.value = results[0].value.data; if (results[1].status === 'fulfilled') expired.value = results[1].value.data; if (results[2].status === 'fulfilled') expiring.value = results[2].value.data; if (results[3].status === 'fulfilled') disposed.value = results[3].value.data; if (results.some(r => r.status === 'rejected')) toast.error('Một số dữ liệu hạn dùng chưa tải được.'); };
const nameOf = id => ingredients.value.find(i => i.id === id)?.name || `#${id}`; const date = d => d ? new Date(d).toLocaleDateString('vi-VN') : '—';
const openBulk = () => { bulkOpen.value = true; selected.value = null; reason.value = ''; modalOpen.value = true; }; const dispose = batch => { bulkOpen.value = false; selected.value = batch; reason.value = ''; modalOpen.value = true; }; const closeModal = () => { modalOpen.value = false; selected.value = null; reason.value = ''; };
const submitDisposal = async () => { if (!reason.value.trim()) { toast.error('Vui lòng nhập lý do tiêu hủy trước khi xác nhận.'); return; } submitting.value = true; try { const url = bulkOpen.value ? '/api/admin/ingredients/expired-batches/dispose-all' : `/api/admin/ingredients/batches/${selected.value.id}/dispose`; await api.post(url, { reason: reason.value.trim() }, headers()); toast.success('Đã ghi nhận tiêu hủy.'); closeModal(); await load(); } catch (e) { toast.error(e.response?.data?.message || 'Không thể tiêu hủy lô.'); } finally { submitting.value = false; } };
onMounted(load);
</script>
<style scoped>
.page{padding:32px;max-width:1400px;margin:auto}.lead{color:var(--text-muted)}.kpis{display:flex;gap:16px;margin:20px 0}.kpis div,.card{background:var(--bg-card);border:1px solid var(--border-light);border-radius:12px;padding:18px}.kpis div{min-width:150px}.kpis b,.kpis span{display:block}.kpis b{font-size:28px;color:var(--primary)}.card{margin:18px 0;overflow:auto}.section-head,.modal-actions{display:flex;justify-content:space-between;align-items:center;gap:12px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--border-light)}button{background:var(--primary);color:#fff;border:0;border-radius:8px;padding:8px 12px;cursor:pointer}.danger{background:var(--primary)}button:disabled{opacity:.5;cursor:not-allowed}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:1000}.modal{background:var(--bg-card);border-radius:14px;padding:24px;width:min(520px,calc(100% - 32px));box-shadow:var(--shadow-lg)}label{display:grid;gap:8px;font-weight:700}textarea{min-height:100px;resize:vertical;border:1px solid var(--border);border-radius:8px;padding:10px;font:inherit}.secondary{background:var(--bg-card2);color:var(--text-heading);border:1px solid var(--border)}
</style>
