<template><main class="event-page"><section><p class="eyebrow">MỘC VỊ EVENT HALL</p><h1>Đặt sảnh sự kiện</h1><p>Yêu cầu tiệc cưới, hội nghị hoặc sinh nhật được tiếp nhận riêng, không cần chọn bàn.</p><form @submit.prevent="submit"><label>Họ tên<input v-model.trim="form.customerName" required /></label><label>Số điện thoại<input v-model.trim="form.customerPhone" required /></label><label>Email<input v-model.trim="form.customerEmail" type="email" /></label><label>Sảnh sự kiện<select v-model.number="form.areaId" required><option :value="null">Chọn sảnh</option><option v-for="area in halls" :key="area.id" :value="area.id">{{ area.nameVi }} · {{ area.minGuestCount }}–{{ area.maxGuestCount }} khách</option></select></label><label>Loại sự kiện<select v-model="form.eventType"><option value="WEDDING">Tiệc cưới</option><option value="CONFERENCE">Hội nghị</option><option value="BIRTHDAY">Sinh nhật</option><option value="OTHER">Khác</option></select></label><label>Số khách<input v-model.number="form.guestCount" min="1" type="number" required /></label><label>Ngày<input v-model="form.reservationDate" type="date" required /></label><label>Giờ<input v-model="form.arrivalTime" type="time" required /></label><label>Số giờ thuê<input v-model.number="form.durationHours" min="1" max="72" type="number" required /></label><label><input v-model="form.decorationRequired" type="checkbox" /> Cần trang trí</label><label><input v-model="form.mcRequired" type="checkbox" /> Cần MC</label><label>Ghi chú<textarea v-model.trim="form.eventNote" maxlength="500" /></label><p v-if="error" class="error">{{ error }}</p><button :disabled="submitting">{{ submitting ? 'Đang gửi...' : 'Gửi yêu cầu đặt sự kiện' }}</button></form><section v-if="result" class="result"><h2>Đã tiếp nhận yêu cầu</h2><p>Mã đặt chỗ: <strong>{{ result.reservationCode }}</strong></p><p>Tiền cọc cần thanh toán: <strong>{{ money(result.depositAmount) }}</strong></p><RouterLink :to="`/reservation-lookup?code=${result.reservationCode}`">Theo dõi yêu cầu</RouterLink></section></section></main></template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import api from '@/services/api'
const form=ref({customerName:'',customerPhone:'',customerEmail:'',areaId:null,eventType:'WEDDING',guestCount:30,reservationDate:new Date().toISOString().slice(0,10),arrivalTime:'',durationHours:4,decorationRequired:false,mcRequired:false,eventNote:''}); const areas=ref([]);const error=ref('');const submitting=ref(false);const result=ref(null);const halls=computed(()=>areas.value.filter(a=>a.areaType==='EVENT_HALL'&&a.status==='ACTIVE'));const money=v=>Number(v||0).toLocaleString('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0});
onMounted(async()=>{try{areas.value=(await api.get('/api/areas')).data||[]}catch{error.value='Không tải được danh sách sảnh sự kiện.'}})
async function submit(){submitting.value=true;error.value='';try{result.value=(await api.post('/api/event-bookings',form.value)).data}catch(e){error.value=e.response?.data?.message||'Không thể gửi yêu cầu.'}finally{submitting.value=false}}
</script>
<style scoped>.event-page{min-height:100vh;padding:48px 16px;background:#ded8c2;color:#201d14}.event-page>section{max-width:760px;margin:auto;background:#fff;padding:32px;border-radius:12px}.eyebrow{color:#5a6e45;font-weight:800}form{display:grid;gap:14px;margin-top:24px}label{display:grid;gap:6px;font-weight:700}input,select,textarea{padding:11px;border:1px solid #cfc7a8;border-radius:7px;font:inherit}button{padding:13px;background:#5a6e45;color:#fff;border:0;border-radius:7px;font-weight:800}.error{color:#a32626}.result{margin-top:24px;padding:18px;background:#f5f4e9;border-radius:8px}</style>
