import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const source = name => readFileSync(fileURLToPath(new URL(name, import.meta.url)), 'utf8')

describe('second UI and business refinement contracts', () => {
  it('shows and prefills the latest exact ingredient import unit price from batch history', () => {
    const ingredients = source('./AdminIngredient.vue')
    expect(ingredients).toContain('Đơn giá nhập gần nhất')
    expect(ingredients).toContain('latestImportPriceText')
    expect(ingredients).toContain('loadLatestImportPrice')
    expect(ingredients).toContain('fetchLatestImportPriceValue')
    expect(ingredients).toContain("`/api/admin/ingredients/${key}/batches`")
    expect(ingredients).toContain('Chưa có dữ liệu trước đó')
    expect(ingredients).toContain('batchForm.value.unitPrice = price')
    expect(ingredients).toContain('applyLatestPriceToInvoiceItem')
    expect(ingredients).toContain('invoice-latest-price')
  })

  it('keeps ingredient pagination, recipe search and import history detail controls explicit', () => {
    const ingredients = source('./AdminIngredient.vue')
    expect(ingredients).toContain('const ingredientPageSize = 7')
    expect(ingredients).toContain('v-for="ing in pagedIngredients"')
    expect(ingredients).toContain('recipeIngredientSearch')
    expect(ingredients).toContain('availableRecipeIngredients')
    expect(ingredients).toContain('usedIds.has')
    expect(ingredients).toContain('class="btn-sm btn-secondary invoice-detail-btn"')
  })

  it('keeps staff/customer edit modals readable and password reset one-time only', () => {
    const staff = source('./AdminStaff.vue')
    expect(staff).toContain('.staff-edit-modal input.g-form-control.staff-locked-username')
    expect(staff).toContain('-webkit-text-fill-color: #FFFFFF')
    expect(staff).toContain('customer-edit-modal')
    expect(staff).toContain('customer-edit-header')
    expect(staff).toContain('customer-edit-footer')
    expect(staff).toContain('temporaryPassword')
    expect(staff).not.toContain('currentPassword')
  })

  it('separates reservation form and summary, paginates areas/preorders, and preserves selected state', () => {
    const reservation = source('./Reservation.vue')
    expect(reservation).toContain('class="booking-layout"')
    expect(reservation).toContain('<form class="reservation-card"')
    expect(reservation).toContain('<aside class="booking-summary"')
    expect(reservation).not.toContain('class="quick-summary"')
    expect(reservation).toContain('const AREA_PAGE_SIZE = 3')
    expect(reservation).toContain('v-for="area in pagedAreas"')
    expect(reservation).toContain('const PREORDER_PAGE_SIZE = 10')
    expect(reservation).toContain('v-for="dish in pagedPreorderMenu"')
    expect(reservation).toContain('cartItems.value')
    expect(reservation).toContain('preorderPageButtons')
    expect(reservation).toContain('compactPageButtons')
    expect(reservation).toContain('selected-dishes-panel')
    expect(reservation).not.toContain('cart-continue-btn')
    expect(reservation).toContain(':disabled="!isDishAvailable(dish)"')
    expect(reservation).toContain('validateSelectedDishes')
    expect(reservation).toContain('await loadQuote()')
    expect(reservation).toContain('isAlcoholicDish')
    expect(reservation).toContain("Number(isAlcoholicDish(a)) - Number(isAlcoholicDish(b))")
    expect(reservation).toContain('syncStep2ValidationErrors')
    expect(reservation).toContain('delete errors.value.arrivalTime')
    expect(reservation).toContain('lateDiningConfirmed.value')
    expect(reservation).toContain('class="dish-card__content"')
    expect(reservation).toContain('class="dish-card__actions"')
    expect(reservation).toContain('class="dish-card__title"')
    expect(reservation).toContain('-webkit-line-clamp: 2')
    expect(reservation).toContain('-webkit-line-clamp: 3')
  })

  it('keeps public and event menus from ranking alcohol before food when no alcohol signal exists', () => {
    const menu = source('./ProductMenu.vue')
    const event = source('./EventBooking.vue')
    expect(menu).toContain('isAlcoholicProduct')
    expect(menu).toContain("Number(isAlcoholicProduct(a)) - Number(isAlcoholicProduct(b))")
    expect(event).toContain('isAlcoholicItem')
    expect(event).toContain("Number(isAlcoholicItem(a)) - Number(isAlcoholicItem(b))")
  })

  it('keeps dine-in full menu compact and sorts available dishes before unavailable dishes', () => {
    const dineIn = source('./DineInOrder.vue')
    expect(dineIn).toContain('const FULL_MENU_PAGE_SIZE = 10')
    expect(dineIn).toContain('v-for="product in pagedFullMenuProducts"')
    expect(dineIn).toContain('sortedFullMenuProducts')
    expect(dineIn).toContain('aAvailable - bAvailable')
    expect(dineIn).toContain('class="menu-pagination"')
  })

  it('shows booking readiness diagnostics to admins and keeps table admin on the admin area endpoint', () => {
    const areas = source('./AdminTableArea.vue')
    const tables = source('./AdminTable.vue')
    expect(areas).toContain('bookingReady')
    expect(areas).toContain('bookingReadyReason')
    expect(areas).toContain('Bàn hoạt động:')
    expect(areas).toContain('Tổng chỗ bàn:')
    expect(areas).toContain('Khu vực ACTIVE chỉ sẵn sàng cho khách đặt')
    expect(tables).toContain("/api/areas/admin")
  })

  it('keeps QR status/regeneration visible and themed', () => {
    const reservation = source('./Reservation.vue')
    expect(reservation).toContain('qrStatusMessage')
    expect(reservation).toContain('paymentStatusMessage')
    expect(reservation).toContain('Chưa ghi nhận thanh toán.')
    expect(reservation).toContain('QR đã hết hạn.')
    expect(reservation).toContain('class="qr-action-btn"')
    expect(reservation).toContain('Đã tạo lại QR thanh toán mới.')
  })

  it('shows admin payment status actions and kitchen started-at progress state', () => {
    const adminOrder = source('./AdminOrder.vue')
    const kitchen = source('./Kitchen.vue')
    expect(adminOrder).toContain('const ORDER_PAGE_SIZE = 10')
    expect(adminOrder).toContain('class="action-stack"')
    expect(adminOrder).toContain('class="pagination-bar hide-on-print"')
    expect(adminOrder).toContain('page: requestedPage - 1')
    expect(adminOrder).toContain('/api/admin/orders/${orderId}/confirm-payment')
    expect(adminOrder).toContain('Xác nhận thanh toán')
    expect(adminOrder).toContain('paymentStatusText')
    expect(adminOrder).toContain('paymentOptionText')
    expect(adminOrder).toContain("if (isPaid && (status === 'UNPAID' || status === 'PENDING' || !status))")
    expect(adminOrder).toContain("3: 'Đã hủy'")
    expect(adminOrder).toContain("6: 'Đang làm một phần'")
    expect(adminOrder).toContain("7: 'Đã phục vụ'")
    expect(kitchen).toContain('dish-in-progress')
    expect(kitchen).toContain('Đang làm')
    expect(kitchen).toContain('startedAt')
  })

  it('distinguishes total and partial load failures on expired-food admin pages', () => {
    const expiredFood = source('./AdminExpiredFood.vue')
    expect(expiredFood).toContain('const pageLoadError = computed(() =>')
    expect(expiredFood).toContain('sectionErrors.expired')
    expect(expiredFood).toContain('sectionErrors.disposed')
    expect(expiredFood).toContain('Không tải được dữ liệu hạn dùng.')
    expect(expiredFood).not.toContain("toast.error('Một số dữ liệu hạn dùng chưa tải được.')")
  })

  it('renders cancellation preview from backend fields instead of frontend refund math', () => {
    const lookup = source('./ReservationLookup.vue')
    expect(lookup).toContain('refundPreview.orderTotalAmount')
    expect(lookup).toContain('refundPreview.paidDepositAmount')
    expect(lookup).toContain('refundPreview.penaltyAmount')
    expect(lookup).toContain('refundPolicyText(refundPreview)')
    expect(lookup).toContain("api.post('/api/reservation-cancellations/preview'")
    expect(lookup).toContain('v-if="canSendCancellationRequest" class="danger-btn"')
    expect(lookup).toContain('cancellationAvailabilityMessage')
    expect(lookup).toContain('white-space: pre-line')
    expect(lookup).toContain('onCancelFieldInput')
    expect(lookup).not.toMatch(/expectedRefundAmount\s*=|refundAmount\s*=/)
  })

  it('uses a compact event hall menu picker instead of rendering every dish as chips', () => {
    const event = source('./EventBooking.vue')
    expect(event).toContain('class="event-menu-picker"')
    expect(event).toContain('v-for="item in pagedMenu"')
    expect(event).toContain('const MENU_PAGE_SIZE = 10')
    expect(event).toContain('menuPageButtons')
    expect(event).toContain('class="event-selected-panel"')
    expect(event).toContain('validCart.value.map')
    expect(event).toContain(':disabled="!isAvailable(item)"')
    expect(event).toContain('validateCart')
    expect(event).not.toContain('cart.map((x) => x.name).join(", ")')
  })
})
